Recomend 'using let binding' on appropriate span
Provide 'consider using a `let` binding' recomendation on the portion of
the statement that doesn't live long enough, instead of the entire
statement.

Instead of:

```bash
error: borrowed value does not live long enough
 --> file.rs:4:13
  |
4 |     let x = Command::new("curl").arg("foo");
  |             ^^^^^^^^^^^^^^^^^^^^           - borrowed value only valid until here
  |             |
  |             does not live long enough
5 | }
  | - borrowed value must be valid until here
  |
help: consider using a `let` binding to increase its lifetime
 --> file.rs:4:5
  |
4 |     let x = Command::new("curl").arg("foo");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

provide:

```bash
error: borrowed value does not live long enough
 --> file.rs:4:13
  |
4 |     let x = Command::new("curl").arg("foo");
  |             ^^^^^^^^^^^^^^^^^^^^           - borrowed value only valid until here
  |             |
  |             does not live long enough
5 | }
  | - borrowed value must be valid until here
  |
help: consider using a `let` binding to increase its lifetime
 --> file.rs:4:5
  |
4 |     let x = Command::new("curl").arg("foo");
  |             ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Fixes #34710.