Detect missing `;` on methods with return type `()`
On a given file `foo.rs`:

```rust
fn foo() {
    return 1;
}

fn bar() {
    qux()
}

fn main() {
    qux()
}

fn qux() -> usize {
    3
}
```

Provide the following output:

```bash
error[E0308]: mismatched types
 --> foo.rs:2:12
  |
1 | fn foo() {
  |          - required because of this return type
2 |     return 1;
  |            ^ expected (), found integral variable
  |
  = note: expected type `()`
  = note:    found type `{integer}`

error[E0308]: mismatched types
 --> foo.rs:6:5
  |
5 | fn bar() {
  |          - required because of this return type
6 |     qux()
  |     ^^^^^- consider adding a semicolon here
  |     |
  |     expected (), found integral variable
  |
  = note: expected type `()`
  = note:    found type `usize`

error[E0308]: mismatched types
  --> foo.rs:10:5
   |
 9 | fn main() {
   |           - required because of this return type
10 |     qux()
   |     ^^^^^- consider adding a semicolon here
   |     |
   |     expected (), found integral variable
   |
   = note: expected type `()`
   = note:    found type `usize`

error: aborting due to 3 previous errors
```