Tweak assoc type obligation spans
* Point at RHS of associated type in obligation span
* Point at `impl` assoc type on projection error
* Mention where implicit `Sized` obligations come from on E0277
* Ordering of `Sized` obligations can affect the presence of the
note. Some tweaks needed to make this the best it can be.
* Move label for `Sized` obligation introduced by type param or assoc type to its own note
* Account for associated types in `Sized` bound error
* New predicate for `Sized` obligations
* Reduce verbosity of recursive obligations
* Fix rustdoc being too smart about `?Sized` bounds
* Point at source of binding lifetime obligation
* review request: Use `note`s instead of labels in E0271

```
error[E0271]: type mismatch resolving `<ModelT as Vehicle>::Color == Blue`
  --> src/test/ui/associated-types/associated-types-binding-to-type-defined-in-supertrait.rs:31:10
   |
31 | fn b() { blue_car(ModelT); } //~ ERROR type mismatch
   |          ^^^^^^^^ type mismatch resolving `<ModelT as Vehicle>::Color == Blue`
   |
note: expected this to be `Blue`
  --> src/test/ui/associated-types/associated-types-binding-to-type-defined-in-supertrait.rs:16:40
   |
16 | impl Vehicle for ModelT { type Color = Black; }
   |                                        ^^^^^
note: required by this bound in `blue_car`
  --> src/test/ui/associated-types/associated-types-binding-to-type-defined-in-supertrait.rs:27:19
   |
27 | fn blue_car<C:Car<Color=Blue>>(c: C) {
   |                   ^^^^^^^^^^
```

* Tweak "required bound" note
* Tweak "expected... found opaque (return) type" labels
* Point at set type in impl assoc type WF errors